<?php
/**
 * =====================================================================================
 * APPLICATION BOOTSTRAP - Main Entry Point
 * =====================================================================================
 *
 * PURPOSE:
 * This is the central bootstrap class that initializes and runs the entire application.
 * It handles class loading, configuration, environment setup, and request routing.
 *
 * INITIALIZATION SEQUENCE:
 * 1. loadCoreClasses() - Loads essential classes (Logger, Database, Router, etc.)
 * 2. loadConfig() - Loads config/config.php and optional config.local.php overrides
 * 3. setupEnvironment() - Sets timezone, locale, charset, and error reporting
 * 4. Creates Router instance and loads route definitions
 *
 * APPLICATION FLOW:
 * ```
 * public/index.php → App::__construct() → App::run()
 *                                              ↓
 *                                        Session::start()
 *                                              ↓
 *                                        Router::dispatch()
 *                                              ↓
 *                                        Controller::method()
 * ```
 *
 * CONFIGURATION:
 * - Main config: src/config/config.php
 * - Local overrides: src/config/config.local.php (gitignored)
 * - Database config: src/config/database.php (generated by installer)
 *
 * KEY METHODS:
 * - App::config('app.debug') - Get nested config value using dot notation
 * - App::isInstalled() - Check for installed.lock file
 * - App::baseUrl() - Get full base URL with protocol
 *
 * RELATED FILES:
 * - public/index.php - Entry point that creates App instance
 * - src/core/Router.php - URL routing and controller dispatch
 * - src/config/routes.php - Route definitions array
 *
 * AI NOTES:
 * - The application starts at public/index.php which defines path constants
 * - Session is ALWAYS started before any request processing
 * - Installation check is done in Router based on URL path
 * - Configuration uses dot notation (e.g., 'app.debug', 'app.timezone')
 *
 * @package KindergartenOrganizer\Core
 * @since 1.0.0
 * =====================================================================================
 */

class App
{
    private static array $config = [];
    private Router $router;

    /**
     * Initialize the application
     */
    public function __construct()
    {
        $this->loadCoreClasses();
        $this->loadConfig();
        $this->setupEnvironment();
        $this->router = new Router();
        $this->router->loadRoutes();
    }

    /**
     * Load core classes
     */
    private function loadCoreClasses(): void
    {
        require_once SRC_PATH . '/core/Logger.php';
        require_once SRC_PATH . '/core/Database.php';
        require_once SRC_PATH . '/core/Router.php';
        require_once SRC_PATH . '/core/Session.php';
        require_once SRC_PATH . '/core/Controller.php';
        require_once SRC_PATH . '/core/Model.php';
        require_once SRC_PATH . '/core/Auth.php';
        require_once SRC_PATH . '/core/Validator.php';

        // Load ChangelogService if exists
        $changelogService = SRC_PATH . '/services/ChangelogService.php';
        if (file_exists($changelogService)) {
            require_once $changelogService;
        }

        // Load ImageProcessor if exists
        $imageProcessor = SRC_PATH . '/services/ImageProcessor.php';
        if (file_exists($imageProcessor)) {
            require_once $imageProcessor;
        }

        // Load Mailer if exists
        $mailer = SRC_PATH . '/services/Mailer.php';
        if (file_exists($mailer)) {
            require_once $mailer;
        }
    }

    /**
     * Load configuration
     */
    private function loadConfig(): void
    {
        $configFile = SRC_PATH . '/config/config.php';
        if (file_exists($configFile)) {
            self::$config = require $configFile;
        }

        // Load local config overrides if exists (for development/debugging)
        $localConfigFile = SRC_PATH . '/config/config.local.php';
        if (file_exists($localConfigFile)) {
            $localConfig = require $localConfigFile;
            self::$config = $this->mergeConfigRecursive(self::$config, $localConfig);
        }
    }

    /**
     * Recursively merge configuration arrays
     */
    private function mergeConfigRecursive(array $base, array $override): array
    {
        foreach ($override as $key => $value) {
            if (isset($base[$key]) && is_array($base[$key]) && is_array($value)) {
                $base[$key] = $this->mergeConfigRecursive($base[$key], $value);
            } else {
                $base[$key] = $value;
            }
        }
        return $base;
    }

    /**
     * Setup environment settings
     */
    private function setupEnvironment(): void
    {
        // Timezone
        $timezone = self::$config['app']['timezone'] ?? 'Europe/Vienna';
        date_default_timezone_set($timezone);

        // Locale
        $locale = self::$config['app']['locale'] ?? 'de_AT.UTF-8';
        setlocale(LC_ALL, $locale);

        // Charset
        mb_internal_encoding(self::$config['app']['charset'] ?? 'UTF-8');

        // Error reporting based on debug mode
        $debug = self::$config['app']['debug'] ?? false;
        if (file_exists(ROOT_PATH . '/storage/debug.flag')) {
            $debug = true;
        }
        if ($debug) {
            error_reporting(E_ALL);
            ini_set('display_errors', '1');
        } else {
            error_reporting(0);
            ini_set('display_errors', '0');
        }
    }

    /**
     * Run the application
     */
    public function run(): void
    {
        // Always start session - needed for flash messages, form validation, etc.
        // Session works regardless of installation status
        Session::start();

        // Get request method and URI
        $method = $_SERVER['REQUEST_METHOD'];
        $uri = $_SERVER['REQUEST_URI'];

        // Dispatch the request
        $this->router->dispatch($method, $uri);
    }

    /**
     * Get configuration value
     */
    public static function config(string $key, $default = null)
    {
        $keys = explode('.', $key);
        $value = self::$config;

        foreach ($keys as $k) {
            if (!isset($value[$k])) {
                return $default;
            }
            $value = $value[$k];
        }

        return $value;
    }

    /**
     * Check if application is installed
     */
    public static function isInstalled(): bool
    {
        return file_exists(ROOT_PATH . '/installed.lock');
    }

    /**
     * Get the base URL
     */
    public static function baseUrl(): string
    {
        $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
        $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
        return $protocol . '://' . $host;
    }
}
